"""
Script: creates data/schema.xlsx

Defines 6 tables with a 4-hop FK chain:
    users → orders → order_items → products → categories

Run from project root:
    python scripts/create_schema_excel.py
"""

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


SCHEMA_ROWS = [
    # ── users ──────────────────────────────────────────────────────────────
    {
        "table_name": "users",
        "table_description": "Registered customers of the platform",
        "column_name": "user_id",
        "data_type": "INTEGER",
        "is_pk": True,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique user identifier",
    },
    {
        "table_name": "users",
        "table_description": "Registered customers of the platform",
        "column_name": "username",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique login handle",
    },
    {
        "table_name": "users",
        "table_description": "Registered customers of the platform",
        "column_name": "email",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "User email address",
    },
    {
        "table_name": "users",
        "table_description": "Registered customers of the platform",
        "column_name": "full_name",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "",
        "fk_column": "",
        "description": "Display name",
    },
    {
        "table_name": "users",
        "table_description": "Registered customers of the platform",
        "column_name": "created_at",
        "data_type": "TIMESTAMP",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Account creation timestamp",
    },
    {
        "table_name": "users",
        "table_description": "Registered customers of the platform",
        "column_name": "is_active",
        "data_type": "BOOLEAN",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Whether account is active",
    },
    # ── categories ─────────────────────────────────────────────────────────
    {
        "table_name": "categories",
        "table_description": "Product category hierarchy",
        "column_name": "category_id",
        "data_type": "INTEGER",
        "is_pk": True,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique category identifier",
    },
    {
        "table_name": "categories",
        "table_description": "Product category hierarchy",
        "column_name": "name",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Category display name",
    },
    {
        "table_name": "categories",
        "table_description": "Product category hierarchy",
        "column_name": "description",
        "data_type": "TEXT",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "",
        "fk_column": "",
        "description": "Category description",
    },
    {
        "table_name": "categories",
        "table_description": "Product category hierarchy",
        "column_name": "parent_category_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "categories",
        "fk_column": "category_id",
        "description": "Self-referential FK for nested categories",
    },
    # ── products ───────────────────────────────────────────────────────────
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "product_id",
        "data_type": "INTEGER",
        "is_pk": True,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique product identifier",
    },
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "name",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Product display name",
    },
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "description",
        "data_type": "TEXT",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "",
        "fk_column": "",
        "description": "Long-form product description",
    },
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "price",
        "data_type": "DECIMAL",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unit price in USD",
    },
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "stock_qty",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Current stock quantity",
    },
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "category_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "categories",
        "fk_column": "category_id",
        "description": "FK to categories table",
    },
    {
        "table_name": "products",
        "table_description": "Product catalogue with pricing and inventory",
        "column_name": "created_at",
        "data_type": "TIMESTAMP",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Date product was added",
    },
    # ── orders ─────────────────────────────────────────────────────────────
    {
        "table_name": "orders",
        "table_description": "Customer purchase orders",
        "column_name": "order_id",
        "data_type": "INTEGER",
        "is_pk": True,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique order identifier",
    },
    {
        "table_name": "orders",
        "table_description": "Customer purchase orders",
        "column_name": "user_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "users",
        "fk_column": "user_id",
        "description": "FK to users table",
    },
    {
        "table_name": "orders",
        "table_description": "Customer purchase orders",
        "column_name": "order_date",
        "data_type": "TIMESTAMP",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "When the order was placed",
    },
    {
        "table_name": "orders",
        "table_description": "Customer purchase orders",
        "column_name": "status",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Order status: pending, shipped, delivered, cancelled",
    },
    {
        "table_name": "orders",
        "table_description": "Customer purchase orders",
        "column_name": "total_amount",
        "data_type": "DECIMAL",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Total order value in USD",
    },
    {
        "table_name": "orders",
        "table_description": "Customer purchase orders",
        "column_name": "shipping_address",
        "data_type": "TEXT",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "",
        "fk_column": "",
        "description": "Delivery address",
    },
    # ── order_items ────────────────────────────────────────────────────────
    {
        "table_name": "order_items",
        "table_description": "Individual line items within an order",
        "column_name": "item_id",
        "data_type": "INTEGER",
        "is_pk": True,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique line-item identifier",
    },
    {
        "table_name": "order_items",
        "table_description": "Individual line items within an order",
        "column_name": "order_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "orders",
        "fk_column": "order_id",
        "description": "FK to orders table",
    },
    {
        "table_name": "order_items",
        "table_description": "Individual line items within an order",
        "column_name": "product_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "products",
        "fk_column": "product_id",
        "description": "FK to products table",
    },
    {
        "table_name": "order_items",
        "table_description": "Individual line items within an order",
        "column_name": "quantity",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Number of units ordered",
    },
    {
        "table_name": "order_items",
        "table_description": "Individual line items within an order",
        "column_name": "unit_price",
        "data_type": "DECIMAL",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Price per unit at time of purchase",
    },
    {
        "table_name": "order_items",
        "table_description": "Individual line items within an order",
        "column_name": "subtotal",
        "data_type": "DECIMAL",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "quantity * unit_price",
    },
    # ── reviews ────────────────────────────────────────────────────────────
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "review_id",
        "data_type": "INTEGER",
        "is_pk": True,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Unique review identifier",
    },
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "user_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "users",
        "fk_column": "user_id",
        "description": "FK to users table",
    },
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "product_id",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "products",
        "fk_column": "product_id",
        "description": "FK to products table",
    },
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "rating",
        "data_type": "INTEGER",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Star rating 1-5",
    },
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "title",
        "data_type": "VARCHAR",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "",
        "fk_column": "",
        "description": "Review headline",
    },
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "body",
        "data_type": "TEXT",
        "is_pk": False,
        "is_nullable": True,
        "fk_table": "",
        "fk_column": "",
        "description": "Full review text",
    },
    {
        "table_name": "reviews",
        "table_description": "Customer product reviews and ratings",
        "column_name": "created_at",
        "data_type": "TIMESTAMP",
        "is_pk": False,
        "is_nullable": False,
        "fk_table": "",
        "fk_column": "",
        "description": "Review submission timestamp",
    },
]


def main():
    output_path = ROOT / "data" / "schema.xlsx"
    output_path.parent.mkdir(exist_ok=True)

    df = pd.DataFrame(SCHEMA_ROWS)

    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="Schema", index=False)

    print(f"Created: {output_path}")
    print(f"  Tables: {df['table_name'].nunique()}")
    print(f"  Rows  : {len(df)}")


if __name__ == "__main__":
    main()
